# Generated by Django 5.0.7 on 2024-07-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area_sqkm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pm25_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('o3_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no2_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.airqualitystation')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.district')),
            ],
        ),
        migrations.CreateModel(
            name='PublicTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('total_vehicles', models.IntegerField()),
                ('electric_vehicles', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector')),
            ],
        ),
        migrations.CreateModel(
            name='GreenSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('electricity_kwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('renewable_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('participants', models.IntegerField()),
                ('initiative_type', models.CharField(max_length=50)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector')),
            ],
        ),
        migrations.AddField(
            model_name='airqualitystation',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector'),
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_waste_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recycled_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainability.sector')),
            ],
        ),
    ]
